# Generated by Django 4.2.7 on 2026-04-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SensorData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("soil_moisture", models.FloatField(verbose_name="土壤湿度")),
                ("temperature", models.FloatField(verbose_name="温度")),
                ("co2", models.FloatField(verbose_name="CO2浓度")),
                ("light", models.FloatField(verbose_name="光照强度")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="采集时间"),
                ),
            ],
            options={
                "verbose_name": "传感器数据",
                "verbose_name_plural": "传感器数据",
                "ordering": ["-created_at"],
            },
        ),
    ]
