# Generated by Django 6.0.4 on 2026-05-23 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataAnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('description', models.TextField(blank=True, default='', verbose_name='说明')),
                ('region', models.CharField(blank=True, default='', max_length=128, verbose_name='分析区域')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '数据分析报告',
                'verbose_name_plural': '数据分析报告',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=64, unique=True, verbose_name='节点编号')),
                ('name', models.CharField(max_length=128, verbose_name='节点名称')),
                ('device_type', models.CharField(default='多合一传感器', max_length=64, verbose_name='设备类型')),
                ('region', models.CharField(blank=True, default='', max_length=128, verbose_name='所属区域')),
                ('install_location', models.CharField(blank=True, default='', max_length=255, verbose_name='安装位置')),
                ('status', models.CharField(choices=[('online', '在线'), ('offline', '离线')], default='online', max_length=16, verbose_name='状态')),
                ('signal_strength', models.PositiveSmallIntegerField(default=4, verbose_name='信号强度')),
                ('battery_level', models.PositiveSmallIntegerField(default=100, verbose_name='电量百分比')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='纬度')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='经度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '监测节点',
                'verbose_name_plural': '监测节点',
                'ordering': ['node_id'],
            },
        ),
        migrations.CreateModel(
            name='AlarmRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', '提示'), ('warn', '警告'), ('critical', '严重')], default='warn', max_length=16, verbose_name='级别')),
                ('title', models.CharField(max_length=128, verbose_name='告警标题')),
                ('message', models.TextField(blank=True, default='', verbose_name='告警描述')),
                ('detail', models.CharField(blank=True, default='', max_length=255, verbose_name='详情')),
                ('metric_value', models.FloatField(blank=True, null=True, verbose_name='当前值')),
                ('threshold', models.FloatField(blank=True, null=True, verbose_name='阈值')),
                ('status', models.CharField(choices=[('active', '未处理'), ('resolved', '已处理')], default='active', max_length=16, verbose_name='处理状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='告警时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alarms', to='dashboard.devicenode', verbose_name='关联节点')),
            ],
            options={
                'verbose_name': '告警记录',
                'verbose_name_plural': '告警记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnvMonitorRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(verbose_name='空气温度(℃)')),
                ('humidity', models.FloatField(verbose_name='空气湿度(%)')),
                ('co2', models.FloatField(verbose_name='CO2(ppm)')),
                ('light', models.FloatField(verbose_name='光照(lux)')),
                ('pressure', models.FloatField(default=101.3, verbose_name='大气压(kPa)')),
                ('air_quality', models.PositiveSmallIntegerField(default=50, verbose_name='空气质量指数')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='采集时间')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='env_records', to='dashboard.devicenode', verbose_name='关联节点')),
            ],
            options={
                'verbose_name': '环境监测记录',
                'verbose_name_plural': '环境监测记录',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='SoilMonitorRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_moisture', models.FloatField(verbose_name='土壤湿度(%)')),
                ('soil_ph', models.FloatField(default=6.8, verbose_name='土壤pH')),
                ('soil_temperature', models.FloatField(verbose_name='土壤温度(℃)')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='采集时间')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soil_records', to='dashboard.devicenode', verbose_name='关联节点')),
            ],
            options={
                'verbose_name': '土壤监测记录',
                'verbose_name_plural': '土壤监测记录',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
